version: 0.2
phases:
  pre_build:
    commands:
      - terraform init
      - terraform validate
  
  build:
    commands:
    ## El objetivo es crear directamente la infra-estructura. 
      - terraform apply -var-file="variables.tfvars" --auto-approve