version: 0.2
phases:
  pre_build:
    commands:
      - terraform init ## Configura el ambiente para poder usar terraform
      - terraform validate ## Escanea en general para comprobar que todo está bien
  
  build:
    commands:
      ## El objetivo es mostrar que se va a hacer 
      - terraform plan -var-file="variables.tfvars" ## se ejecuta terraform plan apuntando al archivo de variables
